version: '3.8'

services:

  backend:
    image: giahuy1412/edtech-be:latest
    container_name: backend_v.1.0.0
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=20.89.64.149

  frontend:
    image: giahuy1412/edtech-fr:latest
    container_name: front
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://20.89.64.149:8080

